"use strict";
/**
 * durable_context.js — writes small "when to use this" files into each AI
 * agent host's documented discoverability location, so an agent actually
 * reaches for Conxa's registered MCP tools instead of never discovering
 * them. Registering the server (mcp_register.js) makes the tools CALLABLE;
 * this makes them FOUND.
 *
 * Called from sync.js right after a workspace's skill list is confirmed by the
 * server (pack.skills written) — deliberately NOT from register-mcp/install
 * time, because a thin installer ships with pack.skills EMPTY (see sync.js);
 * there is nothing real to name until the first successful delta-sync.
 *
 * Only targets hosts we actually registered the MCP server for (reuses
 * mcp_hosts.js's own detect() so the two concerns can't drift apart) — no
 * point advertising tools on a host nothing was registered on.
 *
 * Two write modes:
 *   "dedicated" — a whole file at a path that is exclusively ours (a
 *                 per-workspace skills subdirectory). Plain atomic overwrite,
 *                 no markers needed — nothing else legitimately writes there.
 *   "shared"    — a marker-delimited span inside a file the host itself also
 *                 reads (AGENTS.md, global_rules.md, …). Only the exact span
 *                 between our markers is ever touched; everything else in
 *                 the file is the customer's and is never rewritten. The
 *                 marker pair is the ownership signal — unlike config_edit's
 *                 JSON entries there is no separate schema to check against,
 *                 so "inside our explicitly-labeled span" IS "ours".
 *
 * Paths here are best-effort and lower-confidence than mcp_hosts.js's — verify
 * against each vendor's current docs before shipping.
 */
const path = require("path");
const configEdit = require("./config_edit");
const { HOSTS: MCP_HOSTS, buildContext } = require("./mcp_hosts");

function envOverride(name) {
  const v = process.env[name];
  return v && v.trim() ? v : null;
}

function isHostDetected(id, ctx) {
  const host = MCP_HOSTS.find((h) => h.id === id);
  return !!(host && host.detect(ctx));
}

function claudeConfigDirDurable(ctx) {
  return envOverride("CLAUDE_CONFIG_DIR") || path.join(ctx.home, ".claude");
}

function buildNote(workspace_id, skills) {
  const list = skills.length
    ? skills.map((s) => `- **${s}** — call \`execute_skill\` with workspace \`${workspace_id}\`, skill \`${s}\``).join("\n")
    : "_(no workflows synced yet)_";
  return [
    `Conxa has registered ${skills.length} automated workflow${skills.length === 1 ? "" : "s"} for **${workspace_id}** as MCP tools.`,
    "Call `list_skills` to see current inputs, or `execute_skill` directly once you know which one applies:",
    "",
    list,
  ].join("\n");
}

function buildSkillFrontmatterMd(workspace_id, skills) {
  return [
    "---",
    `name: conxa-${workspace_id}`,
    `description: Conxa automated workflows for ${workspace_id} — call execute_skill to run one`,
    "---",
    "",
    buildNote(workspace_id, skills),
    "",
  ].join("\n");
}

function buildCursorRule(workspace_id, skills) {
  return [
    "---",
    `description: Conxa automated workflows for ${workspace_id}`,
    "alwaysApply: false",
    "---",
    "",
    buildNote(workspace_id, skills),
    "",
  ].join("\n");
}

function markerStart(workspace_id) {
  return `<!-- >>> conxa:${workspace_id} >>> (auto-generated by Conxa — edits here are overwritten on next sync) -->`;
}
function markerEnd(workspace_id) {
  return `<!-- <<< conxa:${workspace_id} <<< -->`;
}

/** Whole file dedicated to us — no markers needed, nothing else writes here. */
async function writeDedicatedFile(filePath, content) {
  const before = configEdit.readRegularFile(filePath);
  if (before.error) return { status: `error:${before.error}` };
  if (before.exists && before.raw === content) return { status: "ok" }; // already current, no-op
  try {
    await configEdit.atomicWrite(filePath, content);
  } catch (e) {
    return { status: `error:write-failed:${e.code || e.message}` };
  }
  return { status: "ok" };
}

/** A shared instructions file — replace only our exact marker-delimited span. */
async function upsertSharedBlock(filePath, workspace_id, blockBody) {
  const start = markerStart(workspace_id);
  const end = markerEnd(workspace_id);
  const before = configEdit.readRegularFile(filePath);
  if (before.error) return { status: `error:${before.error}` };

  const existing = before.exists ? before.raw : "";
  const startIdx = existing.indexOf(start);
  const endIdx = existing.indexOf(end);
  let next;
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    next = existing.slice(0, startIdx) + start + "\n" + blockBody + "\n" + end + existing.slice(endIdx + end.length);
  } else {
    const sep = existing.length === 0 ? "" : existing.endsWith("\n\n") ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
    next = existing + sep + start + "\n" + blockBody + "\n" + end + "\n";
  }
  if (next === existing) return { status: "ok" };

  // Re-read immediately before writing, same CAS discipline as config_edit.js.
  const now = configEdit.readRegularFile(filePath);
  if (now.error) return { status: `error:${now.error}` };
  if ((now.exists ? now.raw : "") !== existing) return { status: "error:changed-underneath" };

  try {
    await configEdit.atomicWrite(filePath, next);
  } catch (e) {
    return { status: `error:write-failed:${e.code || e.message}` };
  }
  return { status: "ok" };
}

// One row per host we advertise discoverability content for. `id` doubles as
// the mcp_hosts.js host id whose detect() gates this row.
const TARGETS = [
  {
    id: "claude-code",
    mode: "dedicated",
    filePath: (ctx, workspace_id) => path.join(claudeConfigDirDurable(ctx), "skills", `conxa-${workspace_id}`, "SKILL.md"),
  },
  {
    id: "cursor",
    mode: "dedicated",
    filePath: (ctx, workspace_id) => path.join(ctx.home, ".cursor", "rules", `conxa-${workspace_id}.mdc`),
  },
  {
    id: "windsurf",
    mode: "shared",
    filePath: (ctx) => path.join(ctx.home, ".codeium", "windsurf", "memories", "global_rules.md"),
  },
  {
    id: "copilot-cli",
    mode: "dedicated",
    filePath: (ctx, workspace_id) => path.join(envOverride("COPILOT_HOME") || path.join(ctx.home, ".copilot"), "skills", `conxa-${workspace_id}`, "SKILL.md"),
  },
  {
    id: "factory",
    mode: "shared",
    filePath: (ctx) => path.join(ctx.home, ".factory", "AGENTS.md"),
  },
  {
    id: "opencode",
    mode: "shared",
    filePath: (ctx) => path.join(ctx.home, ".config", "opencode", "AGENTS.md"),
  },
  {
    id: "gemini-cli",
    mode: "shared",
    filePath: (ctx) => path.join(ctx.home, ".gemini", "GEMINI.md"),
  },
  {
    id: "qwen",
    mode: "shared",
    filePath: (ctx) => path.join(envOverride("QWEN_HOME") || path.join(ctx.home, ".qwen"), "QWEN.md"),
  },
];

/** Update every detected target's discoverability content for one workspace. */
async function updateDurableContext(workspace_id, skills) {
  const ctx = buildContext();
  const note = buildNote(workspace_id, skills);
  const results = [];
  for (const target of TARGETS) {
    if (!isHostDetected(target.id, ctx)) {
      results.push({ target: target.id, status: "skipped:not-detected" });
      continue;
    }
    const filePath = target.filePath(ctx, workspace_id);
    try {
      const r = target.mode === "dedicated"
        ? await writeDedicatedFile(filePath, target.id === "cursor" ? buildCursorRule(workspace_id, skills) : buildSkillFrontmatterMd(workspace_id, skills))
        : await upsertSharedBlock(filePath, workspace_id, note);
      results.push({ target: target.id, file: filePath, ...r });
    } catch (e) {
      results.push({ target: target.id, file: filePath, status: `error:${e.code || e.message}` });
    }
  }
  return results;
}

module.exports = {
  updateDurableContext,
  buildNote,
  buildSkillFrontmatterMd,
  buildCursorRule,
  upsertSharedBlock,
  writeDedicatedFile,
  markerStart,
  markerEnd,
  TARGETS,
};
